/// Flutter icons Custom_Icons1
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom_Icons1
///      fonts:
///       - asset: fonts/Custom_Icons1.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom_Icons1 {
  Custom_Icons1._();

  static const _kFontFam = 'Custom_Icons1';
  static const String? _kFontPkg = null;

  static const IconData search_line = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_square = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
