/// Flutter icons Custom_Icons2
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom_Icons2
///      fonts:
///       - asset: fonts/Custom_Icons2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom_Icons2 {
  Custom_Icons2._();

  static const _kFontFam = 'Custom_Icons2';
  static const String? _kFontPkg = null;

  static const IconData icon__2_ = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
